// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;

public class SlackMessage_equals_5bdc7536f0_Test {

    private SlackMessage slackMessage1;
    private SlackMessage slackMessage2;

    @BeforeEach
    public void setup() {
        slackMessage1 = new SlackMessage();
        slackMessage1.setUnfurlMedia(true);
        slackMessage1.setUnfurlLinks(true);
        slackMessage1.setLinkNames(true);
        slackMessage1.setAttach(Mockito.mock(ArrayList.class));
        slackMessage1.setChannel("channel1");
        slackMessage1.setIcon("icon1");
        slackMessage1.setText("text1");
        slackMessage1.setUsername("username1");

        slackMessage2 = new SlackMessage();
        slackMessage2.setUnfurlMedia(true);
        slackMessage2.setUnfurlLinks(true);
        slackMessage2.setLinkNames(true);
        slackMessage2.setAttach(Mockito.mock(ArrayList.class));
        slackMessage2.setChannel("channel1");
        slackMessage2.setIcon("icon1");
        slackMessage2.setText("text1");
        slackMessage2.setUsername("username1");
    }

    @Test
    public void testEquals_sameObject() {
        Assertions.assertTrue(slackMessage1.equals(slackMessage1));
    }

    @Test
    public void testEquals_differentObjectSameValues() {
        Assertions.assertTrue(slackMessage1.equals(slackMessage2));
    }

    @Test
    public void testEquals_differentObjectDifferentValues() {
        slackMessage2.setUsername("username2");
        Assertions.assertFalse(slackMessage1.equals(slackMessage2));
    }

    @Test
    public void testEquals_nullObject() {
        Assertions.assertFalse(slackMessage1.equals(null));
    }

    @Test
    public void testEquals_differentClass() {
        Assertions.assertFalse(slackMessage1.equals(new String("test")));
    }
}
