// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackMessage_SlackMessage_c507ae43ec_Test {

    private SlackMessage slackMessage;

    @BeforeEach
    public void setUp() {
        slackMessage = new SlackMessage(null, null, null);
    }

    @Test
    public void testSlackMessageWithChannel() {
        String channel = "test_channel";
        slackMessage = new SlackMessage(channel, null, null);
        assertEquals(channel, slackMessage.getChannel());
    }

    @Test
    public void testSlackMessageWithUsername() {
        String username = "test_user";
        slackMessage = new SlackMessage(null, username, null);
        assertEquals(username, slackMessage.getUsername());
    }

    @Test
    public void testSlackMessageWithText() {
        String text = "test_text";
        slackMessage = new SlackMessage(null, null, text);
        assertEquals(text, slackMessage.getText());
    }

    @Test
    public void testSlackMessageWithAllParameters() {
        String channel = "test_channel";
        String username = "test_user";
        String text = "test_text";
        slackMessage = new SlackMessage(channel, username, text);
        assertEquals(channel, slackMessage.getChannel());
        assertEquals(username, slackMessage.getUsername());
        assertEquals(text, slackMessage.getText());
    }
}
