// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.*;

@RunWith(MockitoJUnitRunner.class)
public class SlackAttachment_setAuthorName_55420782e6_Test {

    private SlackAttachment slackAttachment;

    @Before
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetAuthorName() {
        String authorName = "John Doe";
        slackAttachment.setAuthorName(authorName);
        assertEquals("Failure - author names do not match", authorName, slackAttachment.getAuthorName());
    }
    
    @Test
    public void testSetAuthorNameWithNull() {
        String authorName = null;
        slackAttachment.setAuthorName(authorName);
        assertNull("Failure - author name should be null", slackAttachment.getAuthorName());
    }

    @Test
    public void testSetAuthorNameWithEmptyString() {
        String authorName = "";
        slackAttachment.setAuthorName(authorName);
        assertEquals("Failure - author names do not match", authorName, slackAttachment.getAuthorName());
    }
}
