// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackAction_setName_f5bd015150_Test {

    private SlackAction slackAction;

    @BeforeEach
    public void setUp() {
        slackAction = new SlackAction();
    }

    @Test
    public void testSetName() {
        String name = "testName";
        slackAction.setName(name);
        assertEquals(name, slackAction.getName());
    }

    @Test
    public void testSetName_EmptyString() {
        String name = "";
        slackAction.setName(name);
        assertEquals(name, slackAction.getName());
    }
}
