// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.Date;

public class SlackAttachment_setTimestamp_d9ea23f25b_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetTimestamp() {
        Date date = new Date();
        slackAttachment.setTimestamp(date);
        assertEquals(date.getTime() / 1000, slackAttachment.getTimestamp());
    }

    @Test
    public void testSetTimestamp_NullDate() {
        slackAttachment.setTimestamp(null);
        assertEquals(0, slackAttachment.getTimestamp());
    }
}
