// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import java.net.Proxy;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackApi_SlackApi_6fa631f084_Test {

    private SlackApi slackApi;
    private String service;
    private int timeout;
    private Proxy proxy;

    @BeforeEach
    public void setup() {
        service = "http://testService.com";
        timeout = 5000;
        proxy = Proxy.NO_PROXY;
    }

    @Test
    public void testSlackApiWithValidParams() {
        slackApi = new SlackApi(service, timeout, proxy);
        assertEquals(service, slackApi.getService());
        assertEquals(timeout, slackApi.getTimeout());
        assertEquals(proxy, slackApi.getProxy());
    }

    @Test
    public void testSlackApiWithNullService() {
        Throwable exception = assertThrows(IllegalArgumentException.class, () -> {
            new SlackApi(null, timeout, proxy);
        });
        assertEquals("Missing WebHook URL Configuration @ SlackApi", exception.getMessage());
    }

    @Test
    public void testSlackApiWithNullProxy() {
        slackApi = new SlackApi(service, timeout, null);
        assertEquals(service, slackApi.getService());
        assertEquals(timeout, slackApi.getTimeout());
        assertEquals(Proxy.NO_PROXY, slackApi.getProxy());
    }
}
