// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackField_setValue_e5a0cacfb3_Test {

    private SlackField slackField;

    @BeforeEach
    public void setup() {
        slackField = new SlackField();
    }

    @Test
    public void testSetValue() {
        String value = "Test value";
        slackField.setValue(value);
        assertEquals(value, slackField.getValue());
    }

    @Test
    public void testSetValueWithNull() {
        String value = null;
        slackField.setValue(value);
        assertEquals(value, slackField.getValue());
    }
}
