// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackMessage_setText_723ed34229_Test {

    private SlackMessage slackMessage;

    @BeforeEach
    public void setup() {
        slackMessage = new SlackMessage();
    }

    @Test
    public void testSetTextWithNonNullMessage() {
        String message = "Test message";
        slackMessage.setText(message);
        assertEquals(message, slackMessage.getText());
    }

    @Test
    public void testSetTextWithNullMessage() {
        String message = null;
        String initialText = slackMessage.getText();
        slackMessage.setText(message);
        assertEquals(initialText, slackMessage.getText());
    }
}
