// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackAction_setValue_205b9856b4_Test {

    @InjectMocks
    private SlackAction slackAction;

    @BeforeEach
    public void setUp() {
        slackAction = new SlackAction();
    }

    @Test
    public void testSetValue_Success() {
        String expectedValue = "Test Value";
        slackAction.setValue(expectedValue);
        assertEquals(expectedValue, slackAction.getValue(), "The set value should match the get value");
    }

    @Test
    public void testSetValue_Null() {
        String expectedValue = null;
        slackAction.setValue(expectedValue);
        assertEquals(expectedValue, slackAction.getValue(), "The set value should match the get value even if it's null");
    }
}
