// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;

public class SlackAttachment_SlackAttachment_a67c3abe9f_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        slackAttachment = Mockito.mock(SlackAttachment.class);
    }

    @Test
    public void testSlackAttachment_withValidFallback() {
        String fallback = "This is a valid fallback text";
        Mockito.when(slackAttachment.getFallback()).thenReturn(fallback);

        SlackAttachment testAttachment = new SlackAttachment(fallback);
        assertEquals(fallback, testAttachment.getFallback());
    }

    @Test
    public void testSlackAttachment_withEmptyFallback() {
        String fallback = "";
        Mockito.when(slackAttachment.getFallback()).thenReturn(fallback);

        SlackAttachment testAttachment = new SlackAttachment(fallback);
        assertEquals(fallback, testAttachment.getFallback());
    }

    @Test
    public void testSlackAttachment_withNullFallback() {
        String fallback = null;
        Mockito.when(slackAttachment.getFallback()).thenReturn(fallback);

        SlackAttachment testAttachment = new SlackAttachment(fallback);
        assertNull(testAttachment.getFallback());
    }
}
