// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackMessage_toString_2393b88875_Test {
    private SlackMessage slackMessage;

    @BeforeEach
    public void setup() {
        slackMessage = new SlackMessage();
        slackMessage.setAttach(null);
        slackMessage.setChannel("testChannel");
        slackMessage.setIcon("testIcon");
        slackMessage.setSlackMessage(null);
        slackMessage.setText("testText");
        slackMessage.setUsername("testUsername");
        slackMessage.setUnfurlMedia(false);
        slackMessage.setUnfurlLinks(false);
        slackMessage.setLinkNames(1);
    }

    @Test
    public void testToString() {
        String expectedOutput = "SlackMessage{" + "attach=" + null + ", channel='testChannel'" + ", icon='testIcon'"
                + ", slackMessage=" + null + ", text='testText'" + ", username='testUsername'"
                + ", unfurlMedia=" + false + ", unfurlLinks=" + false + ", linkNames=" + 1 + '}';
        assertEquals(expectedOutput, slackMessage.toString());
    }

    @Test
    public void testToStringWithDifferentValues() {
        slackMessage.setChannel("differentChannel");
        slackMessage.setIcon("differentIcon");
        slackMessage.setText("differentText");
        slackMessage.setUsername("differentUsername");

        String expectedOutput = "SlackMessage{" + "attach=" + null + ", channel='differentChannel'" + ", icon='differentIcon'"
                + ", slackMessage=" + null + ", text='differentText'" + ", username='differentUsername'"
                + ", unfurlMedia=" + false + ", unfurlLinks=" + false + ", linkNames=" + 1 + '}';
        assertEquals(expectedOutput, slackMessage.toString());
    }
}
