// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackMessage_removeAttachment_f3cae8f12b_Test {

    private SlackMessage slackMessage;

    @BeforeEach
    public void setup() {
        slackMessage = new SlackMessage();
        slackMessage.setAttach(new ArrayList<>());
        slackMessage.getAttach().add("Attachment1");
        slackMessage.getAttach().add("Attachment2");
        slackMessage.getAttach().add("Attachment3");
    }

    @Test
    public void testRemoveAttachment_Success() {
        slackMessage.removeAttachment(1);
        List<String> expectedAttachments = new ArrayList<>();
        expectedAttachments.add("Attachment1");
        expectedAttachments.add("Attachment3");

        assertEquals(expectedAttachments, slackMessage.getAttach());
    }

    @Test
    public void testRemoveAttachment_InvalidIndex() {
        assertThrows(IndexOutOfBoundsException.class, () -> {
            slackMessage.removeAttachment(5);
        });
    }
}
