// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class SlackApi_SlackApi_9964365bcd_Test {

    private SlackApi slackApi;
    
    @BeforeEach
    public void setUp() {
        slackApi = Mockito.mock(SlackApi.class);
    }

    @Test
    public void testSlackApiWithValidService() {
        String service = "validService";
        when(slackApi.getService()).thenReturn(service);
        assertEquals(service, slackApi.getService());
    }

    @Test
    public void testSlackApiWithInvalidService() {
        String service = "";
        when(slackApi.getService()).thenReturn(service);
        assertEquals(service, slackApi.getService());
    }
}
