// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackActionStyle_getCode_ef3482daf5_Test {

    @InjectMocks
    private SlackActionStyle slackActionStyle;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetCode_Success() {
        String expectedCode = "success";
        slackActionStyle.setCode(expectedCode);
        String actualCode = slackActionStyle.getCode();
        assertEquals(expectedCode, actualCode, "Expected code does not match the actual code");
    }

    @Test
    public void testGetCode_Failure() {
        String expectedCode = "failure";
        slackActionStyle.setCode(expectedCode);
        String actualCode = slackActionStyle.getCode();
        assertEquals(expectedCode, actualCode, "Expected code does not match the actual code");
    }
}
