// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import com.google.gson.JsonObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackAction_SlackAction_a6813d4ffc_Test {

    private SlackAction slackAction;

    @BeforeEach
    public void setup() {
        slackAction = new SlackAction("testName", "testText", SlackActionType.BUTTON, "testValue");
    }

    @Test
    public void testName() {
        assertEquals("testName", slackAction.getName());
    }

    @Test
    public void testText() {
        assertEquals("testText", slackAction.getText());
    }

    @Test
    public void testType() {
        assertEquals(SlackActionType.BUTTON, slackAction.getType());
    }

    @Test
    public void testValue() {
        assertEquals("testValue", slackAction.getValue());
    }
}
