// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import com.google.gson.JsonObject;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

public class SlackAction_setType_e4400cbce3_Test {

    private SlackAction slackAction;

    @Before
    public void setUp() {
        slackAction = new SlackAction();
    }

    @Test
    public void testSetType() {
        SlackActionType type = Mockito.mock(SlackActionType.class);
        slackAction.setType(type);
        Assert.assertEquals(type, slackAction.getType());
    }

    @Test
    public void testSetType_Null() {
        slackAction.setType(null);
        Assert.assertNull(slackAction.getType());
    }
}
