// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackAttachment_setTitleLink_92bea32be0_Test {

    @InjectMocks
    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetTitleLink() {
        String titleLink = "http://example.com";
        slackAttachment.setTitleLink(titleLink);
        assertEquals(titleLink, slackAttachment.getTitleLink(), "The title link should match the provided string");
    }

    @Test
    public void testSetTitleLink_Null() {
        String titleLink = null;
        slackAttachment.setTitleLink(titleLink);
        assertEquals(titleLink, slackAttachment.getTitleLink(), "The title link should be null");
    }
}
