// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
@SpringBootTest
public class SlackAttachment_setAuthorLink_dcc5fdecbe_Test {

    private SlackAttachment slackAttachment;

    @Before
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetAuthorLink() {
        String authorLink = "http://example.com";
        slackAttachment.setAuthorLink(authorLink);
        assertEquals(authorLink, slackAttachment.getAuthorLink());
    }

    @Test
    public void testSetAuthorLinkWithNull() {
        slackAttachment.setAuthorLink(null);
        assertEquals(null, slackAttachment.getAuthorLink());
    }

    // TODO: Add more test cases here for different scenarios.
}
