// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import com.google.gson.JsonObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class SlackAction_setStyle_1379dcce13_Test {

    private SlackAction slackAction;

    @BeforeEach
    public void setUp() {
        slackAction = new SlackAction();
    }

    @Test
    public void testSetStyle_Success() {
        // TODO: Change the style as per your requirement
        SlackActionStyle style = SlackActionStyle.DANGER;
        slackAction.setStyle(style);

        assertEquals(style, slackAction.getStyle());
    }

    @Test
    public void testSetStyle_NullStyle() {
        assertThrows(NullPointerException.class, () -> {
            slackAction.setStyle(null);
        });
    }

    @Test
    public void testSetStyle_InvalidStyle() {
        // Mocking the SlackActionStyle
        SlackActionStyle style = Mockito.mock(SlackActionStyle.class);
        Mockito.when(style.toJson()).thenReturn(new JsonObject());

        assertThrows(IllegalArgumentException.class, () -> {
            slackAction.setStyle(style);
        });
    }
}
