// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackAttachment_setPretext_5afe9c6253_Test {
    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetPretext() {
        String pretext = "Test Pretext";
        slackAttachment.setPretext(pretext);
        assertEquals(pretext, slackAttachment.getPretext());
    }

    @Test
    public void testSetPretext_Null() {
        String pretext = null;
        slackAttachment.setPretext(pretext);
        assertEquals(pretext, slackAttachment.getPretext());
    }
}
