// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackMessage_setUnfurlLinks_c83997d8b9_Test {

    private SlackMessage slackMessage;

    @BeforeEach
    public void setup() {
        slackMessage = new SlackMessage();
    }

    @Test
    public void testSetUnfurlLinksTrue() {
        slackMessage.setUnfurlLinks(true);
        assertEquals(true, slackMessage.isUnfurlLinks());
    }

    @Test
    public void testSetUnfurlLinksFalse() {
        slackMessage.setUnfurlLinks(false);
        assertEquals(false, slackMessage.isUnfurlLinks());
    }
}
