// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class SlackAction_getName_4ad76af4d7_Test {

    @Test
    public void testGetName_WhenNameIsNotNull() {
        // Mock the external service
        SlackAction slackAction = Mockito.mock(SlackAction.class);

        // Define the return value for method getName()
        Mockito.when(slackAction.getName()).thenReturn("Test Name");

        // Execute the method to test
        String name = slackAction.getName();

        // Assert the expected and actual output
        Assertions.assertEquals("Test Name", name);
    }

    @Test
    public void testGetName_WhenNameIsNull() {
        // Mock the external service
        SlackAction slackAction = Mockito.mock(SlackAction.class);

        // Define the return value for method getName()
        Mockito.when(slackAction.getName()).thenReturn(null);

        // Execute the method to test
        String name = slackAction.getName();

        // Assert the expected and actual output
        Assertions.assertNull(name);
    }
}
