// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class SlackAttachment_setTitle_480927a769_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setup() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetTitle() {
        String title = "Test Title";
        slackAttachment.setTitle(title);
        Assertions.assertEquals(title, slackAttachment.getTitle(), "The title should match the set value");
    }

    @Test
    public void testSetTitleWithEmptyString() {
        String title = "";
        slackAttachment.setTitle(title);
        Assertions.assertEquals(title, slackAttachment.getTitle(), "The title should match the set value even if it is an empty string");
    }

    @Test
    public void testSetTitleWithNull() {
        String title = null;
        slackAttachment.setTitle(title);
        Assertions.assertNull(slackAttachment.getTitle(), "The title should be null if set value is null");
    }
}
