// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class SlackAction_getValue_2ee290d3be_Test {

    @Mock
    private SlackAction slackAction;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetValue() {
        String expectedValue = "testValue";
        Mockito.when(slackAction.getValue()).thenReturn(expectedValue);

        String actualValue = slackAction.getValue();
        Assertions.assertEquals(expectedValue, actualValue, "Expected value doesn't match with actual value");
    }

    @Test
    public void testGetValue_Null() {
        Mockito.when(slackAction.getValue()).thenReturn(null);

        String actualValue = slackAction.getValue();
        Assertions.assertNull(actualValue, "Expected null but found some value");
    }
}
