// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class SlackAttachment_removeAction_2d61558025_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        slackAttachment = Mockito.spy(new SlackAttachment());
        List<String> actions = new ArrayList<>();
        actions.add("Action1");
        actions.add("Action2");
        actions.add("Action3");
        Mockito.doReturn(actions).when(slackAttachment).getActions();
    }

    @Test
    public void testRemoveAction_Success() {
        slackAttachment.removeAction(1);
        assertEquals(2, slackAttachment.getActions().size());
        assertEquals("Action1", slackAttachment.getActions().get(0));
        assertEquals("Action3", slackAttachment.getActions().get(1));
    }

    @Test
    public void testRemoveAction_IndexOutOfBounds() {
        assertThrows(IndexOutOfBoundsException.class, () -> slackAttachment.removeAction(3));
    }
}
