// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class SlackField_toString_2393b88875_Test {

    @Test
    public void testToString_AllParametersPresent() {
        SlackField slackField = Mockito.mock(SlackField.class);
        Mockito.when(slackField.toString()).thenReturn("SlackField{allowMarkdown=true, shorten=false, title='title', value='value'}");
        
        String actualOutput = slackField.toString();
        String expectedOutput = "SlackField{allowMarkdown=true, shorten=false, title='title', value='value'}";
        
        Assertions.assertEquals(expectedOutput, actualOutput);
    }

    @Test
    public void testToString_SomeParametersMissing() {
        SlackField slackField = Mockito.mock(SlackField.class);
        Mockito.when(slackField.toString()).thenReturn("SlackField{allowMarkdown=true, shorten=false, title='null', value='null'}");
        
        String actualOutput = slackField.toString();
        String expectedOutput = "SlackField{allowMarkdown=true, shorten=false, title='null', value='null'}";
        
        Assertions.assertEquals(expectedOutput, actualOutput);
    }
}
