// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class SlackAction_getText_b0281f8eee_Test {

    private SlackAction slackAction;

    @BeforeEach
    public void setup() {
        slackAction = Mockito.mock(SlackAction.class);
        Mockito.when(slackAction.getText()).thenReturn("Test Text");
    }

    @Test
    public void testGetText_Success() {
        String expectedText = "Test Text";
        String actualText = slackAction.getText();
        Assertions.assertEquals(expectedText, actualText, "The expected text does not match the actual text");
    }

    @Test
    public void testGetText_Failure() {
        String expectedText = "Wrong Text";
        String actualText = slackAction.getText();
        Assertions.assertNotEquals(expectedText, actualText, "The expected text should not match the actual text");
    }
}
