// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackAttachment_removeFields_a5af773703_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setup() {
        slackAttachment = new SlackAttachment();
        ArrayList<String> fields = new ArrayList<>();
        fields.add("Field1");
        fields.add("Field2");
        fields.add("Field3");
        slackAttachment.setFields(fields);
    }

    @Test
    public void testRemoveFields_ValidIndex() {
        slackAttachment.removeFields(1);
        assertEquals(2, slackAttachment.getFields().size());
        assertFalse(slackAttachment.getFields().contains("Field2"));
    }

    @Test
    public void testRemoveFields_InvalidIndex() {
        assertThrows(IndexOutOfBoundsException.class, () -> {
            slackAttachment.removeFields(5);
        });
    }

    @Test
    public void testRemoveFields_NegativeIndex() {
        assertThrows(IndexOutOfBoundsException.class, () -> {
            slackAttachment.removeFields(-1);
        });
    }
}
