// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;

public class SlackAction_getStyle_72450b8f37_Test {

    @Test
    public void testGetStyleSuccess() {
        SlackAction slackAction = Mockito.mock(SlackAction.class);
        SlackActionStyle style = SlackActionStyle.BUTTON;
        Mockito.when(slackAction.getStyle()).thenReturn(style);

        SlackActionStyle result = slackAction.getStyle();
        assertEquals(style, result, "getStyle method does not return correct style");
    }

    @Test
    public void testGetStyleFailure() {
        SlackAction slackAction = Mockito.mock(SlackAction.class);
        Mockito.when(slackAction.getStyle()).thenReturn(null);

        SlackActionStyle result = slackAction.getStyle();
        assertNull(result, "getStyle method should return null when style is not set");
    }
}
