// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;

public class SlackApi_call_9c44adb473_Test {

    private SlackApi slackApi;

    @Mock
    private SlackMessage message;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        slackApi = new SlackApi();
    }

    @Test
    public void testCallWithNonNullMessage() {
        JsonObject preparedMessage = new JsonObject();
        when(message.prepare()).thenReturn(preparedMessage);

        slackApi.call(message);

        verify(message, times(1)).prepare();
        verify(slackApi, times(1)).send(preparedMessage);
    }

    @Test
    public void testCallWithNullMessage() {
        slackApi.call(null);

        verify(message, times(0)).prepare();
        verify(slackApi, times(0)).send(any(JsonObject.class));
    }
}
