// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackMessage_SlackMessage_4d8f61b03c_Test {
    
    private SlackMessage slackMessage;

    @BeforeEach
    public void setUp() {
        slackMessage = mock(SlackMessage.class);
    }

    @Test
    public void testSlackMessageWithTextOnly() {
        String text = "Test message";
        SlackMessage message = new SlackMessage(text);
        assertEquals(text, message.getText());
    }

    @Test
    public void testSlackMessageWithEmptyText() {
        String text = "";
        SlackMessage message = new SlackMessage(text);
        assertEquals(text, message.getText());
    }
}
