// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.net.Proxy;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;

public class SlackApi_SlackApi_1bee4b38f2_Test {

    @Mock
    private Proxy proxy;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSlackApiSuccessCase() {
        String expectedService = "testService";
        SlackApi slackApi = new SlackApi(expectedService, proxy);

        assertEquals("Service should match the expected service", expectedService, slackApi.getService());
        verify(proxy, times(1)).connect(any());
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSlackApiFailureCase() {
        String expectedService = ""; // TODO: User is supposed to change the value
        new SlackApi(expectedService, proxy);
    }

}
