// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackMessage_setIcon_d46fa7b009_Test {

    private SlackMessage slackMessage;

    @BeforeEach
    public void setUp() {
        slackMessage = new SlackMessage();
    }

    @Test
    public void testSetIconWithNonNullIcon() {
        String expectedIcon = "test_icon";
        slackMessage.setIcon(expectedIcon);
        assertEquals(expectedIcon, slackMessage.getIcon());
    }

    @Test
    public void testSetIconWithNullIcon() {
        String defaultIcon = slackMessage.getIcon();
        slackMessage.setIcon(null);
        assertEquals(defaultIcon, slackMessage.getIcon());
    }
}
