// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.util.ArrayList;
import java.util.List;

public class SlackAttachment_prepareActions_fb039e8b5d_Test {

    @Mock
    private SlackAction slackAction;

    private List<SlackAction> actions;

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
        actions = new ArrayList<>();
    }

    @Test
    public void testPrepareActions_EmptyList() {
        JsonArray data = prepareActions();
        Assert.assertTrue(data.size() == 0);
    }

    @Test
    public void testPrepareActions_NonEmptyList() {
        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("test", "value");
        Mockito.when(slackAction.toJson()).thenReturn(jsonObject);
        actions.add(slackAction);

        JsonArray data = prepareActions();
        Assert.assertEquals(1, data.size());
        Assert.assertEquals(jsonObject, data.get(0));
    }

    private JsonArray prepareActions() {
        final JsonArray data = new JsonArray();
        for (SlackAction action : actions) {
            data.add(action.toJson());
        }

        return data;
    }
}
