// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SlackAttachment_setAuthorIcon_dc79d5ce2d_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    void testSetAuthorIcon() {
        String authorIcon = "http://example.com/icon.png";
        slackAttachment.setAuthorIcon(authorIcon);
        assertEquals(authorIcon, slackAttachment.getAuthorIcon());
    }

    @Test
    void testSetAuthorIcon_Null() {
        String authorIcon = null;
        slackAttachment.setAuthorIcon(authorIcon);
        assertNull(slackAttachment.getAuthorIcon());
    }
}
