// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackAttachment_setFooterIcon_129889182a_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setup() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetFooterIcon_Success() {
        String footerIcon = "https://example.com/icon.png";
        slackAttachment.setFooterIcon(footerIcon);
        assertEquals(footerIcon, slackAttachment.getFooterIcon());
    }

    @Test
    public void testSetFooterIcon_Null() {
        slackAttachment.setFooterIcon(null);
        assertEquals(null, slackAttachment.getFooterIcon());
    }
}
