// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

public class SlackException_SlackException_b51b342f9e_Test {

    private Throwable throwableMock;
    private SlackException slackException;

    @Before
    public void setup() {
        throwableMock = Mockito.mock(Throwable.class);
    }

    @Test
    public void testSlackException_Success() {
        slackException = new SlackException(throwableMock);
        Assert.assertNotNull(slackException);
        Assert.assertEquals(throwableMock, slackException.getCause());
    }

    @Test(expected = NullPointerException.class)
    public void testSlackException_Null() {
        slackException = new SlackException(null);
    }
}
