// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class SlackAttachment_setColor_87398aa5d0_Test {
    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetColorWithHexColor() {
        String color = "#FFFFFF";
        slackAttachment.setColor(color);
        assertEquals(color, slackAttachment.getColor());
    }

    @Test
    public void testSetColorWithPreDefinedColor() {
        String color = "good";
        slackAttachment.setColor(color);
        assertEquals(color, slackAttachment.getColor());
    }

    @Test
    public void testSetColorWithInvalidHexColor() {
        String color = "#ZZZZZZ";
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            slackAttachment.setColor(color);
        });

        String expectedMessage = "Invalid Hex Color @ SlackAttachment";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }

    @Test
    public void testSetColorWithInvalidPreDefinedColor() {
        String color = "invalid";
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            slackAttachment.setColor(color);
        });

        String expectedMessage = "Invalid PreDefined Color @ SlackAttachment";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }
}
