// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;

public class SlackAttachment_isHex_87b084b25e_Test {

    @InjectMocks
    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsHex_ValidHex() {
        String hex = "ff00ff";
        assertTrue(slackAttachment.isHex(hex));
    }

    @Test
    public void testIsHex_InvalidHex() {
        String notHex = "gg11hh";
        assertFalse(slackAttachment.isHex(notHex));
    }

    @Test
    public void testIsHex_EmptyString() {
        String empty = "";
        assertFalse(slackAttachment.isHex(empty));
    }

    @Test
    public void testIsHex_NullString() {
        String nullString = null;
        assertThrows(NullPointerException.class, () -> {
            slackAttachment.isHex(nullString);
        });
    }
}
