// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackAttachment_setThumbUrl_e58c653690_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetThumbUrl() {
        String thumbUrl = "http://example.com/thumb.jpg";
        slackAttachment.setThumbUrl(thumbUrl);
        assertEquals(thumbUrl, slackAttachment.getThumbUrl(), "The thumbUrl should match the set value");
    }

    @Test
    public void testSetThumbUrl_Null() {
        String thumbUrl = null;
        slackAttachment.setThumbUrl(thumbUrl);
        assertEquals(thumbUrl, slackAttachment.getThumbUrl(), "The thumbUrl should be null when set to null");
    }
}
