// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackAttachment_addFields_4eb597945f_Test {

    private SlackAttachment slackAttachment;
    private SlackField slackField;

    @BeforeEach
    public void setup() {
        slackAttachment = new SlackAttachment();
        slackField = mock(SlackField.class); // mock the SlackField
    }

    @Test
    public void testAddFields_Success() {
        slackAttachment.addFields(slackField); 
        assertNotNull(slackAttachment.getFields());
        assertEquals(1, slackAttachment.getFields().size());
    }

    @Test
    public void testAddFields_MultipleFields() {
        slackAttachment.addFields(slackField); 
        slackAttachment.addFields(slackField); 
        assertNotNull(slackAttachment.getFields());
        assertEquals(2, slackAttachment.getFields().size());
    }

    @Test
    public void testAddFields_NullField() {
        slackAttachment.addFields(null); 
        assertNotNull(slackAttachment.getFields());
        assertEquals(0, slackAttachment.getFields().size());
    }
}
