// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class SlackAttachment_setText_2fd4e0cfb3_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setup() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetText() {
        String text = "Sample Text";
        slackAttachment.setText(text);
        assertEquals(text, slackAttachment.getText());
    }

    @Test
    public void testSetText_Empty() {
        String text = "";
        slackAttachment.setText(text);
        assertEquals(text, slackAttachment.getText());
    }

    @Test
    public void testSetText_Null() {
        String text = null;
        slackAttachment.setText(text);
        assertEquals(text, slackAttachment.getText());
    }
}
