// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

@RunWith(MockitoJUnitRunner.class)
@SpringBootTest
public class SlackAttachment_setFields_d17073feab_Test {

    private SlackAttachment slackAttachment;

    @Before
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetFields() {
        SlackField field1 = new SlackField();
        field1.setTitle("Title1");
        field1.setValue("Value1");

        SlackField field2 = new SlackField();
        field2.setTitle("Title2");
        field2.setValue("Value2");

        List<SlackField> fields = Arrays.asList(field1, field2);

        slackAttachment.setFields(fields);

        assertNotNull(slackAttachment.getFields());
        assertEquals(2, slackAttachment.getFields().size());
        assertEquals("Title1", slackAttachment.getFields().get(0).getTitle());
        assertEquals("Value1", slackAttachment.getFields().get(0).getValue());
        assertEquals("Title2", slackAttachment.getFields().get(1).getTitle());
        assertEquals("Value2", slackAttachment.getFields().get(1).getValue());
    }

    @Test
    public void testSetFields_EmptyList() {
        List<SlackField> fields = Arrays.asList();

        slackAttachment.setFields(fields);

        assertNotNull(slackAttachment.getFields());
        assertEquals(0, slackAttachment.getFields().size());
    }
}
