// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;

public class SlackAttachment_setFooter_16c18db9f2_Test {

    private SlackAttachment slackAttachment;

    @BeforeEach
    public void setUp() {
        slackAttachment = new SlackAttachment();
    }

    @Test
    public void testSetFooter() {
        String footer = "Test Footer";
        slackAttachment.setFooter(footer);
        Assertions.assertEquals(footer, slackAttachment.getFooter(), "Footer should be set correctly");
    }

    @Test
    public void testSetFooterNull() {
        String footer = null;
        slackAttachment.setFooter(footer);
        Assertions.assertNull(slackAttachment.getFooter(), "Footer should be null");
    }
}
