// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackMessage_setUnfurlMedia_d02f8b70b9_Test {

    private SlackMessage slackMessage;

    @BeforeEach
    public void setUp() {
        slackMessage = new SlackMessage();
    }

    @Test
    public void testSetUnfurlMedia_True() {
        slackMessage.setUnfurlMedia(true);
        assertEquals(true, slackMessage.isUnfurlMedia());
    }

    @Test
    public void testSetUnfurlMedia_False() {
        slackMessage.setUnfurlMedia(false);
        assertEquals(false, slackMessage.isUnfurlMedia());
    }
}
