// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;

public class SlackMessage_setLinkNames_b374411481_Test {

    private SlackMessage slackMessage;

    @BeforeEach
    public void setUp() {
        slackMessage = new SlackMessage();
    }

    @Test
    public void testSetLinkNamesTrue() {
        slackMessage.setLinkNames(true);
        Assertions.assertTrue(slackMessage.isLinkNames());
    }

    @Test
    public void testSetLinkNamesFalse() {
        slackMessage.setLinkNames(false);
        Assertions.assertFalse(slackMessage.isLinkNames());
    }
}
