// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SlackMessage_SlackMessage_de20b79a06_Test {

    @Mock
    SlackMessage slackMessage;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSlackMessageSuccess() {
        String expectedUsername = "JohnDoe";
        String expectedText = "Hello, World!";
        slackMessage = new SlackMessage(expectedUsername, expectedText);
        assertEquals(expectedUsername, slackMessage.getUsername());
        assertEquals(expectedText, slackMessage.getText());
    }

    @Test
    public void testSlackMessageFailure() {
        String expectedUsername = "";
        String expectedText = "";
        slackMessage = new SlackMessage(expectedUsername, expectedText);
        assertEquals(expectedUsername, slackMessage.getUsername());
        assertEquals(expectedText, slackMessage.getText());
    }
}
