// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class SlackField_equals_5bdc7536f0_Test {

    private SlackField slackField;

    @BeforeEach
    public void setup() {
        slackField = new SlackField();
        slackField.setShorten(true);
        slackField.setAllowMarkdown(true);
        slackField.setTitle("Test Title");
        slackField.setValue("Test Value");
    }

    @Test
    public void testEqualsMethod_SameObject() {
        assertTrue(slackField.equals(slackField));
    }

    @Test
    public void testEqualsMethod_DifferentObjectSameValues() {
        SlackField anotherSlackField = new SlackField();
        anotherSlackField.setShorten(true);
        anotherSlackField.setAllowMarkdown(true);
        anotherSlackField.setTitle("Test Title");
        anotherSlackField.setValue("Test Value");

        assertTrue(slackField.equals(anotherSlackField));
    }

    @Test
    public void testEqualsMethod_DifferentObjectDifferentValues() {
        SlackField anotherSlackField = new SlackField();
        anotherSlackField.setShorten(false);
        anotherSlackField.setAllowMarkdown(false);
        anotherSlackField.setTitle("Different Title");
        anotherSlackField.setValue("Different Value");

        assertFalse(slackField.equals(anotherSlackField));
    }

    @Test
    public void testEqualsMethod_NullObject() {
        assertFalse(slackField.equals(null));
    }
}
