// Test generated by RoostGPT for test slack-webhook-java using AI Type Open AI and AI Model gpt-4

package net.gpedro.integrations.slack;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class SlackMessage_addAttachments_6ae1f294af_Test {
    
    @Mock
    private SlackAttachment attachment;

    private SlackMessage slackMessage;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        slackMessage = new SlackMessage();
    }

    @Test
    public void testAddAttachments() {
        slackMessage.addAttachments(attachment);
        verify(attachment, times(1)).add(attachment);
        assertEquals(slackMessage, attachment);
    }

    @Test
    public void testAddAttachments_Null() {
        slackMessage.addAttachments(null);
        verify(attachment, times(0)).add(null);
        assertEquals(slackMessage, attachment);
    }
}
